import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Shared/Header";
import BottomNav from "@/components/Shared/BottomNav";
import Loader from "@/components/Shared/Loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Loader /> */}
        <Header />
        <div className="pb-24 mb-44">{children}</div>
        <BottomNav />
      </body>
    </html>
  );
}
